### ISSUE TITLE
Story Arc

### ISSUE THREAD

**Issue by mariushop** [retextjs/ideas#1]
Hi Titus, 
Thank you for your work on retextjs. I used your simplicity plugin in an [online editor](https://eddtor.com). I'm planning to use more of your great plugins. 

I have this dream of a tool that draws (graphically) the story arc based on text analysis. It could map your writing to the classical arcs as enumerated by Lafrance:
1. Rags to Riches [a complete rise];
2. Riches to Rags [a fall];
3. Man in a Hole [fall then rise];
4. Icarus [rise then fall];
5. Cinderella [rise then fall then rise];
6. Oedipus [fall then rise then fall].

I know it's a moonshot, but yeah.

**Comment by wooorm** [comment]
That sounds awesome! 🌝

Very vague though! How would it work?

I’m thinking of analysing each paragraph, normalising scores per section or chapter, and plotting in a line chart (think download count charts)?

What would you visualise though? You could detect keywords, and count where they occur the most?

P.S. what’s a lafrance? 😛

**Comment by mariushop** [comment]
_Analysing each paragraph, normalising scores, and plotting a line chart_ is an awfully good idea to start this. 
 "Analysing for what, exactly?" is a minor problem, to be addressed in countless hours of try&fail, frustration and, ultimately, despair.

But seriously: sentiment analysis.

As long as we're hallucinating: the line chart should run from top to bottom, take as baseline the left margin of the text. Here, it's easier to show than describe:
![eddtor-plotline](https://user-images.githubusercontent.com/4264640/33603212-81bf83a4-d9ba-11e7-9a65-b86f65297a70.jpg)
Line is exaggerated to make a point (sic!).

P.S. a lafrance is a simplified vonnegut 😅  [proof] (https://media.licdn.com/mpr/mpr/p/5/005/05d/2a6/051a828.jpg)

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @mariushop  !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/retextjs/retext/discussions/categories/ideas will be the home for ideas going forward.
