### ISSUE TITLE
Discord classifiers

### ISSUE THREAD

**Issue by vccortez** [retextjs/ideas#3]
This `unified` ecosystem is really interesting and I wanna try using it to improve my Discord chatting bot.

Similarly to `retext-emoji` or `retext-syntax-mention`, the idea is to create plugins for classifying Discord mentions such as `@member`, `#channel` and `@role` strings, and their emojis as well.

Each of these elements follow a predictable pattern, so it should be doable. I just need to learn the plugin API.

However, I am a little unsure if `retext` is the correct tool for me, or if I should only use `unified`, because I intend to use the syntax tree with my chat bot, and not the markdown generated by `retext` with `retext-stringify`.

**Comment by wooorm** [comment]
Hey @vekat! That sounds pretty interesting.

> However, I am a little unsure if retext is the correct tool for me, or if I should only use unified, because I intend to use the syntax tree with my chat bot, and not the markdown generated by retext with retext-stringify.

Ah, so *remark* is the markdown thing, *retext* is the natural language thing. And *unified* is the thing under everything.

What you’re planning on doing sounds a bit more like syntax, so it’s not *really* the thing that retext does.
retext does know a bit about syntax, but inside it’s ecosystem “syntax” is used to ignore things. Such as [`retext-syntax-mentions`](https://github.com/retextjs/retext-syntax-mentions) and [`retext-syntax-urls`](https://github.com/retextjs/retext-syntax-urls).

**Comment by wooorm** [comment]
I think this issue is solved / question is answered, but feel free to comment and I’ll re-open!
