### ISSUE TITLE
Future of Retext i18n

### ISSUE THREAD

**Issue by robinmetral** [retextjs/ideas#4]
What are the plans for internationalizing Retext?

I've seen there's already been some work on Dutch, unfortunately I'm interested in French :slightly_smiling_face: :fr: 

An awesome and probably-not-so-hard first step could be making `retext-smartypants` extensions for other languages. For example French uses « these quote marks ».

How can I help?

**Comment by wooorm** [comment]
It's not too hard to support another latin-script, as retext-english and retext-dutch can be used as reference implementations and they're not too big.

And retext-smartypants already let's you customise quotes, right?

**Comment by robinmetral** [comment]
Well as far as I've seen the quotes options don't go as far as the french `« »`.

Or do you think we could add more customisation options to `retext-smartypants`?

**Comment by wooorm** [comment]
Ah sorry, I was thinking of [`retext-quotes`](https://github.com/retextjs/retext-quotes)! That supports guillemets, but warns about them instead of changing them.

What is actually your goal? Why the interest in French quotes?

**Comment by robinmetral** [comment]
My interest is actually in using Remark on French-language websites, but following the locale's typographic rules :slightly_smiling_face: 

For English remark-smartypants is taking care of this, and I'd love to see alternatives for other languages/locales!

**Comment by wooorm** [comment]
> My interest is actually in using Remark on French-language websites, but following the locale's typographic rules 🙂

Alright, well I’d appreciate an issue/PR on retext-smartypants to discuss that.
And I’d also love something like [parse-english](https://github.com/wooorm/parse-english/blob/master/index.js) but for French, but I’m not French enough to pull that off! 🍷🧀🥖

> For English remark-smartypants is taking care of this, and I'd love to see alternatives for other languages/locales!

Yep, same! 👍

**Comment by robinmetral** [comment]
Sounds great! I'd be happy to help :slightly_smiling_face: 

Logistically do you think this can happen within retext-smartypants? Or should I fork and translate it?

**Comment by wooorm** [comment]
If the change is just the "straight" quotes to «french» quotes, that could go in retext-smartypants!

**Comment by robinmetral** [comment]
Well, there's the whole question of spacing in French typography. For instance, we put a thin non-breaking-space before a semicolon.

Then these rules differ based on locale. For example in France there's a nonbreaking space in front of a colon, where in French-speaking Switzerland it's a _thin_ nonbreaking space. There's a whole [French Wikipedia article](https://fr.wikipedia.org/wiki/Comparatif_des_diff%C3%A9rents_codes_typographiques_francophones) about these differences!

If I wanted to make a retext plugin with all the correct typographic rules for French based on locale, how should I proceed?

In the meantime the « french » quotes could indeed go in retext-smartypants as another option :slightly_smiling_face: I'll try to make a PR for this.

**Comment by wooorm** [comment]
> In the meantime the « french » quotes could indeed go in retext-smartypants as another option 🙂 I'll try to make a PR for this.

👍

> If I wanted to make a retext plugin with all the correct typographic rules for French based on locale, how should I proceed?

Re all the spaces and other things: sounds more like a different plugin. I’d suggest doing something like retext-smartypants, but for many more things. Or maybe several small plugins (in a monorepo?). `retext-typography-french-semicolon-spaces`, `retext-typography-french-quotes`, etc... And then publish a [preset](https://github.com/unifiedjs/unified#preset) as `retext-typography-french` for all the small plugins? 🤷‍♂️

**Comment by robinmetral** [comment]
Thanks for the quick reply, sounds great!

I'm not sure I'm personally up to the task for the monorepo, but I'll start with the PR to `retext-smartypants` and see where it gets me :slightly_smiling_face:
