### ISSUE TITLE
TextRank implementation for retext

### ISSUE THREAD

**Issue by ChristianMurphy** [retextjs/ideas#5]
### Subject of the feature

Add an implementation of `TextRank` build with `retext`.
TextRank Paper: https://web.eecs.umich.edu/~mihalcea/papers/mihalcea.emnlp04.pdf
Some sample implementations:
* https://github.com/dpressel/textrank-js
* https://github.com/bibhuticoder/summaryjs

### Problem

TextRank specializes in automated summarization of natural language text bodies.

**Comment by ChristianMurphy** [comment]
Suggested in Spectrum Chat https://spectrum.chat/unified/retext/automatic-summarization-plugins~1998a926-41b9-46c9-bcac-957e7ad7b869

**Comment by wooorm** [comment]
Cool idea!

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @ChristianMurphy !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/retextjs/retext/discussions/categories/ideas will be the home for ideas going forward.
