### ISSUE TITLE
Plugin that checks for user-specified custom words

### ISSUE THREAD

**Issue by tml428** [retextjs/ideas#6]
### Subject of the feature
Retext plugin that screens for words in a custom input list.
Should be pretty similar to [retext-profanities](https://github.com/retextjs/retext-profanities) except it accepts an array of words instead of [using the words defined in `cuss` ](https://github.com/retextjs/retext-profanities/blob/main/factory.js#L34)

### Problem

There seems to be no plugin that takes in custom input and checks against custom words.

### Expected behavior

Plugin should accept custom words array and output warnings/errors if a match occurs when comparing target sentence and the custom word list.

### Alternatives

Refactor one of the existing plugins such as `retext-profanities` or `retext-redundant-acronyms` to accept custom inputs. But they are great by themselves for their purposes so repurposing them probably isn't very wise. 😅

**Comment by wooorm** [comment]
Hi Michelle! https://github.com/bkeepers/retext-words might be what you’re looking for, but hasn’t been updated recently.

**Comment by tml428** [comment]
Hi @wooorm , thanks for the pointer! Is there any plan for `retext-words` to get published to npm? Otherwise, what would you suggest I do if want to use the plugin in my code?

**Comment by wooorm** [comment]
Hey, thanks for your patience.

`retext-words` is not maintained here. You could ask there to publish it, although I think bkeepers is doing other stuff right now.
And: you can use projects from github in npm too: `npm install bkeepers/retext-words`
Finally, you could also do something like that yourself? Update that project, publish it?

**Comment by tml428** [comment]
Thanks for the advice!
